package uz.sonic.hr.task;

import com.lowagie.text.*;
import com.lowagie.text.pdf.PdfPCell;
import com.lowagie.text.pdf.PdfPTable;
import com.lowagie.text.pdf.PdfWriter;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.server.ResponseStatusException;
import org.springframework.http.HttpStatus;
import uz.sonic.hr.common.dto.Dtos.EmployeeStats;
import uz.sonic.hr.common.dto.Dtos.MonthlyStats;
import uz.sonic.hr.team.TeamMembership;
import uz.sonic.hr.team.TeamService;

import java.awt.Color;
import java.io.ByteArrayOutputStream;
import java.time.YearMonth;
import java.time.format.TextStyle;
import java.util.Locale;

/** Renders a team's monthly statistics into a styled PDF report. */
@Service
@RequiredArgsConstructor
public class MonthlyReportService {

    private static final Color BRAND = new Color(0x4f, 0x46, 0xe5);
    private static final Color SLATE = new Color(0x33, 0x41, 0x55);
    private static final Color MUTED = new Color(0x94, 0xa3, 0xb8);
    private static final Color HEADER_BG = new Color(0xee, 0xf2, 0xff);
    private static final Color ROW_ALT = new Color(0xf8, 0xfa, 0xfc);

    private final StatsService statsService;

    @Transactional(readOnly = true)
    public byte[] monthlyReport(TeamMembership viewer, int year, int month) {
        TeamService.requireManager(viewer);
        MonthlyStats stats = statsService.monthly(viewer, year, month);
        String teamName = viewer.getTeam().getName();
        String monthName = YearMonth.of(year, month).getMonth().getDisplayName(TextStyle.FULL, Locale.ENGLISH);

        try (ByteArrayOutputStream out = new ByteArrayOutputStream()) {
            Document doc = new Document(PageSize.A4, 42, 42, 48, 42);
            PdfWriter.getInstance(doc, out);
            doc.open();

            Font h1 = font(22, Font.BOLD, SLATE);
            Font sub = font(11, Font.NORMAL, MUTED);
            Font h2 = font(13, Font.BOLD, SLATE);

            Paragraph title = new Paragraph(teamName, h1);
            doc.add(title);
            doc.add(new Paragraph("Monthly report — " + monthName + " " + year, sub));
            doc.add(chunkRule());

            // Summary cards row
            doc.add(spacer(10));
            doc.add(summaryTable(stats));

            // Employee of the month
            doc.add(spacer(16));
            if (stats.employeeOfMonth() != null) {
                PdfPTable eom = new PdfPTable(1);
                eom.setWidthPercentage(100);
                PdfPCell cell = new PdfPCell();
                cell.setBackgroundColor(HEADER_BG);
                cell.setBorderColor(new Color(0xc7, 0xd2, 0xfe));
                cell.setPadding(12);
                Paragraph p = new Paragraph();
                p.add(new Chunk("⭐  Employee of the month:  ", font(12, Font.NORMAL, SLATE)));
                p.add(new Chunk(stats.employeeOfMonth(), font(13, Font.BOLD, BRAND)));
                cell.addElement(p);
                eom.addCell(cell);
                doc.add(eom);
            }

            // Per-member table
            doc.add(spacer(18));
            doc.add(new Paragraph("Member performance", h2));
            doc.add(spacer(6));
            doc.add(memberTable(stats));

            doc.add(spacer(24));
            Paragraph footer = new Paragraph(
                    "Generated by HR System on " + java.time.LocalDate.now(), font(9, Font.ITALIC, MUTED));
            footer.setAlignment(Element.ALIGN_CENTER);
            doc.add(footer);

            doc.close();
            return out.toByteArray();
        } catch (Exception e) {
            throw new ResponseStatusException(HttpStatus.INTERNAL_SERVER_ERROR, "Failed to generate report", e);
        }
    }

    private PdfPTable summaryTable(MonthlyStats s) throws DocumentException {
        String[][] cards = {
                {"Created", String.valueOf(s.totalCreated())},
                {"Completed", String.valueOf(s.totalCompleted())},
                {"In progress", String.valueOf(s.totalInProgress())},
                {"In review", String.valueOf(s.totalTesting())},
                {"Overdue", String.valueOf(s.totalOverdue())},
        };
        PdfPTable table = new PdfPTable(cards.length);
        table.setWidthPercentage(100);
        for (String[] card : cards) {
            PdfPCell c = new PdfPCell();
            c.setBorderColor(new Color(0xe2, 0xe8, 0xf0));
            c.setPadding(10);
            c.setHorizontalAlignment(Element.ALIGN_CENTER);
            Paragraph value = new Paragraph(card[1], font(20, Font.BOLD, BRAND));
            value.setAlignment(Element.ALIGN_CENTER);
            Paragraph label = new Paragraph(card[0], font(9, Font.NORMAL, MUTED));
            label.setAlignment(Element.ALIGN_CENTER);
            c.addElement(value);
            c.addElement(label);
            table.addCell(c);
        }
        return table;
    }

    private PdfPTable memberTable(MonthlyStats s) throws DocumentException {
        PdfPTable table = new PdfPTable(new float[]{3, 1.2f, 1.4f, 1.4f, 1.2f, 1.3f, 1.4f});
        table.setWidthPercentage(100);
        String[] heads = {"Member", "Taken", "Completed", "On time", "Overdue", "Reviewed", "Avg hrs"};
        for (String h : heads) {
            PdfPCell hc = new PdfPCell(new Phrase(h, font(9, Font.BOLD, SLATE)));
            hc.setBackgroundColor(HEADER_BG);
            hc.setBorderColor(new Color(0xe2, 0xe8, 0xf0));
            hc.setPadding(7);
            table.addCell(hc);
        }
        if (s.perEmployee().isEmpty()) {
            PdfPCell empty = new PdfPCell(new Phrase("No activity this month", font(10, Font.ITALIC, MUTED)));
            empty.setColspan(heads.length);
            empty.setPadding(12);
            empty.setHorizontalAlignment(Element.ALIGN_CENTER);
            table.addCell(empty);
            return table;
        }
        int i = 0;
        for (EmployeeStats e : s.perEmployee()) {
            Color bg = (i++ % 2 == 0) ? Color.WHITE : ROW_ALT;
            table.addCell(bodyCell(e.fullName(), bg, Element.ALIGN_LEFT, Font.BOLD));
            table.addCell(bodyCell(String.valueOf(e.taken()), bg, Element.ALIGN_CENTER, Font.NORMAL));
            table.addCell(bodyCell(String.valueOf(e.completed()), bg, Element.ALIGN_CENTER, Font.NORMAL));
            table.addCell(bodyCell(String.valueOf(e.onTime()), bg, Element.ALIGN_CENTER, Font.NORMAL));
            table.addCell(bodyCell(String.valueOf(e.overdue()), bg, Element.ALIGN_CENTER, Font.NORMAL));
            table.addCell(bodyCell(String.valueOf(e.reviewed()), bg, Element.ALIGN_CENTER, Font.NORMAL));
            table.addCell(bodyCell(e.avgCompletionHours() != null ? String.valueOf(e.avgCompletionHours()) : "—",
                    bg, Element.ALIGN_CENTER, Font.NORMAL));
        }
        return table;
    }

    private PdfPCell bodyCell(String text, Color bg, int align, int style) {
        PdfPCell c = new PdfPCell(new Phrase(text, font(10, style, SLATE)));
        c.setBackgroundColor(bg);
        c.setBorderColor(new Color(0xe2, 0xe8, 0xf0));
        c.setPadding(7);
        c.setHorizontalAlignment(align);
        return c;
    }

    private static Font font(float size, int style, Color color) {
        Font f = FontFactory.getFont(FontFactory.HELVETICA, size, style);
        f.setColor(color);
        return f;
    }

    private static Paragraph spacer(float height) {
        Paragraph p = new Paragraph(" ");
        p.setLeading(height);
        return p;
    }

    private static Paragraph chunkRule() {
        Paragraph p = new Paragraph();
        p.add(new Chunk(new com.lowagie.text.pdf.draw.LineSeparator(0.7f, 100, new Color(0xe2, 0xe8, 0xf0), Element.ALIGN_CENTER, -4)));
        return p;
    }
}
